### ISSUE TITLE
Split the webhook code apart

### ISSUE THREAD

**Issue by rossdargan** [scottrobertson/monzo-to-ynab#11]
I think we should move everything out of the flask code and have a separate monzo object. Currently it's really hard to test without spinning up flask. Ideally we should be able to just pass a JSON object into a class without needing the web server.

A post 1.0 thing though!

**Comment by scottrobertson** [comment]
Agreed. The Flask code should be tiny :)

**Comment by scottrobertson** [comment]
This needs to be done before we can do #14 too
