### ISSUE TITLE
Match data from previous transcation

### ISSUE THREAD

**Issue by rossdargan** [scottrobertson/monzo-to-ynab#12]
Just a heads up on what I'm working on adding now.

When we get a new transaction I now look for a previous transaction for this payee, and get the category set, and the payee actually used (some people tidy up the names of the payees).

Are you happy for me to sneak this in before 1.0?

**Comment by scottrobertson** [comment]
Yeah, that is a good idea. Auto filling the category based on the previous transaction will work really nicely.

**Comment by rossdargan** [comment]
resolved with check in 484f4e81f11afc518f7ad46139c7f026b9cdbea2

**Comment by scottrobertson** [comment]
@rossdargan with big changes like that, we should really still use branches and PR them in so that we can test.

**Comment by rossdargan** [comment]
Fair point - to be honest it's more my lack of familiarity with git that's caused it.

**Comment by scottrobertson** [comment]
No worries. Just for future note :) not all changes need a new branch, just bigger ones like this.
