### ISSUE TITLE
The healthcheck is currently broken for docker

### ISSUE THREAD

**Issue by rossdargan** [scottrobertson/monzo-to-ynab#21]
The healthcheck is currently broken for docker - I suspect because we will now be getting a 302 probably for /

This is how we currently do the check... but it's not great:
HEALTHCHECK CMD curl --fail http://localhost:5000/ || exit 1

Maybe we could add a proper healthcheck endpoint... If we knew we were getting errors with the sync it would be good to be able to report it here.

**Comment by scottrobertson** [comment]
Hmm. `curl --fail http://localhost:5000/ || exit 1` returns totally fine for me though when running the app.

How are you running the health check manually?
