### ISSUE TITLE
Slowness causing timeouts

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/monzo-to-ynab#3]
For larger accounts, we are facing timeouts. This is an issue on something like Heroku as the have a hard coded 30-second timeout.

I am going to look into how/if we can background these requests without bringing in another dependency such as redis for queuing.

**Comment by scottrobertson** [comment]
If doing it without a dependency is not possible then we will just need to make it optional. So have the ability to use Celery + Redis.

**Comment by scottrobertson** [comment]
@rossdargan this is actually probably quite easy. We just need to define the client outside of the main.py controller. I will move it to settings.py to test for now

**Comment by scottrobertson** [comment]
Ok, while this has helped, heroku has a boot timeout, which is 60 seconds, so that now times out :(

**Comment by rossdargan** [comment]
bah. Could you add an option to do the load on either boot, or first transaction add (boot works best for docker)

**Comment by scottrobertson** [comment]
The timeout is even lower when adding on the first transaction (30 seconds. boot is 60 seconds).

**Comment by scottrobertson** [comment]
Gonna look into how we are populating sqlite. It feels like it takes a LONG time.

**Comment by scottrobertson** [comment]
@rossdargan as for your "sync before pushing" comment. It seems that the client does that internally.

**Comment by rossdargan** [comment]
Fab.... however should we do it before checking for payees?

**Comment by scottrobertson** [comment]
Yeah that is a good point

**Comment by scottrobertson** [comment]
I think this is ok now. It's still not as fast as i would want it to be, but it's < 10 seconds so it should be fine. If we can work out another way around this, it would be good, but for now this is fine.

**Comment by rossdargan** [comment]
Agreed :)
