### ISSUE TITLE
Docker Size

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/monzo-to-ynab#7]
@rossdargan the docker image is HUGE. Not sure why that python image is so big, some of the layers are > 150mb which is crazy. We need to look into an alpine based image at least.

**Comment by scottrobertson** [comment]
There are `-slim` versions of each of the versions.

**Comment by rossdargan** [comment]
Are you looking into this or would you like me to?

**Comment by scottrobertson** [comment]
I can at some point tonight. But if you want, here is some starter code:

```
FROM python:2.7.13-alpine

MAINTAINER Ross Dargan

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc
```

**Comment by rossdargan** [comment]
Getting a little closer

```
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc g++ python python-dev py-pip
```

Need to resolve the following though:

Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
** make sure the development packages of libxml2 and libxslt are installed **
Package 'libffi', required by 'world', not found
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

**Comment by scottrobertson** [comment]
You should be able to just install it using apk https://pkgs.alpinelinux.org/package/v3.3/main/x86/libffi

**Comment by rossdargan** [comment]
Ok. It was 314 MB... I've pushed the new one to docker hub so lets see what size it thinks it is now it's over to alpine!

I need to update the readme.md to include some getting started stuff for docker (I like to give a sample docker-compose) - are you happy having that info added?

**Comment by rossdargan** [comment]
147 MB now. A bit slimmer :)

**Comment by scottrobertson** [comment]
It was only 314? The base image is around 900 on its own, not sure how it got down to 314. Awesome job!
